/**
 * Real Byte-Pair Encoding (tiktoken) Engine
 * ==========================================
 * Reproduces the exact tokenization of OpenAI's tiktoken (o200k_base, cl100k_base,
 * p50k_base) and Meta Llama 3, using the REAL vocabulary & merge-rank data shipped
 * in tokenizers/data/*.js (generated by tools/convert_vocab.js from the official
 * .tiktoken files and Llama 3's tokenizer.json).
 *
 * The algorithm is the standard byte-level BPE:
 *   1. Pre-tokenize with the GPT-2 regex
 *   2. UTF-8 encode each chunk and map bytes to the GPT-2 byte-level alphabet
 *      (space -> "Ġ", newline -> "Ċ", tab -> "Ĩ", high bytes -> U+0100+)
 *   3. Greedily merge the lowest-rank adjacent pair until no pair is in ranks
 *   4. Look up each merged part's id in the vocab
 */

(function () {
  // ---- GPT-2 byte <-> unicode alphabet ------------------------------------
  const byteToChar = new Map();
  const charToByte = new Map();
  {
    const bs = [];
    const cs = [];
    for (let i = 0x21; i <= 0x7e; i++) { bs.push(i); cs.push(i); }
    for (let i = 0xa1; i <= 0xac; i++) { bs.push(i); cs.push(i); }
    for (let i = 0xae; i <= 0xff; i++) { bs.push(i); cs.push(i); }
    let n = 0;
    for (let b = 0; b < 256; b++) {
      if (!bs.includes(b)) { bs.push(b); cs.push(256 + n); n++; }
    }
    for (let i = 0; i < bs.length; i++) {
      byteToChar.set(bs[i], String.fromCharCode(cs[i]));
      charToByte.set(String.fromCharCode(cs[i]), bs[i]);
    }
  }

  window.BYTE_LEVEL = { byteToChar, charToByte };

  // ---- lazy data loader ----------------------------------------------------
  const loaders = {};
  window.loadTiktokenData = function loadTiktokenData(name) {
    if (window.TIKTOKEN_DATA && window.TIKTOKEN_DATA[name]) return Promise.resolve();
    if (!loaders[name]) {
      loaders[name] = new Promise((resolve, reject) => {
        const s = document.createElement("script");
        s.src = "tokenizers/data/" + name + ".js";
        s.onload = () => resolve();
        s.onerror = () => reject(new Error("Failed to load tokenizer data: " + name));
        document.head.appendChild(s);
      });
    }
    return loaders[name];
  };

  // ---- engine ----------------------------------------------------------------
  window.TiktokenTokenizer = class TiktokenTokenizer {
    constructor(modelConfig) {
      this.modelConfig = modelConfig;
      this.data = modelConfig.tiktokenData;
      this.specialTokens = this.data.special || {};
      // The per-encoding pat_str (from the official registry) is authoritative
      // for exact models; a model-level regex is only a fallback.
      this.regex = this.data.patStr
        ? this._compilePatStr(this.data.patStr)
        : (modelConfig.regex || (window.TOKENIZER_VOCABS && window.TOKENIZER_VOCABS.bpeRegex));
      this._ensureParsed();
    }

    _compilePatStr(patStr) {
      // JS has no inline (?i: flag — convert to (?: (equivalent for the
      // contraction groups used by tiktoken patterns)
      const src = (patStr || "").replace(/\(\?i:/g, "(?:");
      try {
        return new RegExp(src, "gu");
      } catch (e) {
        return window.TOKENIZER_VOCABS && window.TOKENIZER_VOCABS.bpeRegex;
      }
    }

    _ensureParsed() {
      if (this.data.__parsed) { Object.assign(this, this.data.__parsed); return; }
      const ranks = new Map(); // byte-level string -> merge rank
      const vocab = new Map(); // byte-level string -> token id
      const idInfo = new Map(); // id -> { key, text }

      for (const line of this.data.ranks.split("\n")) {
        if (!line) continue;
        const sp = line.indexOf(" ");
        ranks.set(line.slice(0, sp), parseInt(line.slice(sp + 1), 10));
      }

      // tiktoken files: rank === id, so vocab is the same content as ranks
      const vocabText = this.data.vocab !== undefined ? this.data.vocab : this.data.ranks;
      for (const line of vocabText.split("\n")) {
        if (!line) continue;
        const sp = line.indexOf(" ");
        const key = line.slice(0, sp);
        const id = parseInt(line.slice(sp + 1), 10);
        vocab.set(key, id);
        if (!idInfo.has(id)) idInfo.set(id, { key, text: this._keyToText(key) });
      }

      const parsed = { _ranks: ranks, _vocab: vocab, _idInfo: idInfo };
      this.data.__parsed = parsed;
      Object.assign(this, parsed);
    }

    _keyToText(key) {
      // decode a byte-level key back into its UTF-8 text (lossless for valid utf-8)
      try {
        const bytes = [];
        for (const c of key) {
          const b = charToByte.get(c);
          if (b !== undefined) bytes.push(b);
          else bytes.push(...new TextEncoder().encode(c));
        }
        return new TextDecoder("utf-8").decode(Uint8Array.from(bytes));
      } catch (e) {
        return key;
      }
    }

    // ---- public API -----------------------------------------------------------
    tokenize(text) {
      if (!text) return [];
      const tokens = [];
      for (const part of this._splitBySpecial(text)) {
        if (part.special) {
          const id = this.specialTokens[part.text];
          tokens.push({
            index: tokens.length,
            id,
            text: part.text,
            displaySubword: part.text,
            bytes: Array.from(new TextEncoder().encode(part.text)),
            hexBytes: [],
            start: part.start,
            end: part.end,
            type: "special"
          });
          continue;
        }
        this._encodePiece(part.text, part.start, tokens);
      }
      return tokens;
    }

    getMergeSteps(text) {
      if (!text) return [];
      const steps = [
        { step: 1, title: "Raw Input Text", description: `"${text}"`, state: [text] },
      ];
      // use the first regex chunk
      const regex = this.regex;
      regex.lastIndex = 0;
      const m = regex.exec(text);
      const chunk = m ? m[0] : text;
      if (!chunk) return steps;

      const { keys } = this._encodeChunkToKeys(chunk);
      steps.push({ step: 2, title: "Character / Byte Split", description: "Split into initial character bytes", state: [...keys] });

      let parts = [...keys];
      let stepNum = 3;
      while (parts.length > 1 && stepNum <= 7) {
        let bestIdx = -1, bestRank = Infinity;
        for (let i = 0; i < parts.length - 1; i++) {
          const r = this._ranks.get(parts[i] + parts[i + 1]);
          if (r !== undefined && r < bestRank) { bestRank = r; bestIdx = i; }
        }
        if (bestIdx === -1) break;
        const merged = parts[bestIdx] + parts[bestIdx + 1];
        parts[bestIdx] = merged;
        parts.splice(bestIdx + 1, 1);
        steps.push({
          step: stepNum++,
          title: "BPE Pair Merge",
          description: `Merged into "${this._shorten(merged)}" (rank ${bestRank})`,
          mergedPair: { result: merged, rank: bestRank },
          state: [...parts]
        });
      }
      return steps;
    }

    _shorten(s) {
      return s.length > 24 ? s.slice(0, 24) + "…" : s;
    }

    // ---- internals ---------------------------------------------------------------
    _splitBySpecial(text) {
      const keys = Object.keys(this.specialTokens).sort((a, b) => b.length - a.length);
      if (!keys.length) return [{ text, start: 0, special: false }];
      const parts = [];
      let segStart = 0, i = 0;
      while (i < text.length) {
        const k = keys.find(k => text.startsWith(k, i));
        if (k) {
          if (i > segStart) parts.push({ text: text.slice(segStart, i), start: segStart, special: false });
          parts.push({ text: k, start: i, special: true });
          i += k.length;
          segStart = i;
        } else i++;
      }
      if (segStart < text.length) parts.push({ text: text.slice(segStart), start: segStart, special: false });
      return parts;
    }

    _encodePiece(text, baseStart, tokens) {
      const regex = this.regex;
      regex.lastIndex = 0;
      let lastPos = 0, m;
      while ((m = regex.exec(text)) !== null) {
        if (m.index > lastPos) this._encodeChunk(text.slice(lastPos, m.index), baseStart + lastPos, tokens);
        this._encodeChunk(m[0], baseStart + m.index, tokens);
        lastPos = regex.lastIndex;
        if (m[0].length === 0) regex.lastIndex++;
      }
      if (lastPos < text.length) this._encodeChunk(text.slice(lastPos), baseStart + lastPos, tokens);
    }

    _encodeChunkToKeys(chunk) {
      // byte-level char per byte + byte-index -> char-index map.
      // IMPORTANT: encode by code point so surrogate pairs (emoji) are not
      // mangled into replacement characters.
      const keys = [];
      const charIdxAt = [];
      for (let i = 0; i < chunk.length; ) {
        const cp = chunk.codePointAt(i);
        const units = cp > 0xffff ? 2 : 1;
        const cb = new TextEncoder().encode(String.fromCodePoint(cp));
        for (let b = 0; b < cb.length; b++) {
          charIdxAt.push(i);
          keys.push(byteToChar.get(cb[b]));
        }
        i += units;
      }
      return { keys, charIdxAt };
    }

    _encodeChunk(chunk, start, tokens) {
      if (!chunk) return;
      const { keys, charIdxAt } = this._encodeChunkToKeys(chunk);

      let parts = keys.map(k => k);
      while (parts.length > 1) {
        let bestIdx = -1, bestRank = Infinity;
        for (let i = 0; i < parts.length - 1; i++) {
          const r = this._ranks.get(parts[i] + parts[i + 1]);
          if (r !== undefined && r < bestRank) { bestRank = r; bestIdx = i; }
        }
        if (bestIdx === -1) break;
        parts[bestIdx] += parts[bestIdx + 1];
        parts.splice(bestIdx + 1, 1);
      }

      let byteCursor = 0;
      for (const part of parts) {
        const len = part.length;
        const bStart = byteCursor;
        const bEnd = byteCursor + len;
        byteCursor = bEnd;

        let id = this._vocab.get(part);
        if (id === undefined) id = this._ranks.get(part); // byte-level fallback

        const cStart = charIdxAt[bStart];
        const cEnd = bEnd > 0 ? charIdxAt[bEnd - 1] + 1 : cStart;
        const rawText = chunk.slice(cStart, cEnd);
        const bytes = Array.from(new TextEncoder().encode(rawText));

        tokens.push({
          index: tokens.length,
          id,
          text: rawText,
          displaySubword: part,
          bytes,
          hexBytes: bytes.map(b => "0x" + b.toString(16).padStart(2, "0").toUpperCase()),
          start: start + cStart,
          end: start + cEnd,
          type: this.getTokenType(rawText)
        });
      }
    }

    getTokenType(str) {
      if (/^\s+$/.test(str)) return "whitespace";
      if (/^<\|.*\|>|\[.*\]|<s>|<\/s>$/.test(str)) return "special";
      if (/^\d+$/.test(str)) return "number";
      if (/^[^\w\s]+$/.test(str)) return "symbol";
      if (/[\u1000-\uFFFF]/.test(str)) return "unicode";
      return "word";
    }
  };
})();
